### ISSUE TITLE
Crash of the metaorchestrator in the installation process

### ISSUE THREAD

**Issue by andreacv98** [fluidos-project/fluidos-modelbased-metaorchestrator#32]
Hi everyone!

First time ever that I try the FLUIDOS Metaorchestrator and I started with the setup suggested in your README, but something is not working, in fact I would like to address this possibile bug in the installation process of the FLUIDOS meta-orchestrator, or maybe it is something I am missing in the installation process.

I followed the instructions for installing the operator both in development and production mode, both of them return me error when trying to run the operator.

Development mode installation
---
  1. Creation of the cluster as the kind instruction provided
```shell
  kind create cluster --name foo --config utils/cluster-multi-worker.yaml --kubeconfig utils/examples/dublin-kubeconfig.yaml
  ```
  2. Export of the KUBECONFIG as the one `provided` to the kind instruction (to be sure to use the right cluster)
```shell
  export KUBECONFIG=utils/examples/dublin-kubeconfig.yaml
  ```
  3. Created a venv where I installed kopf as suggested in the pip installation after activated it  
  4. Run the kopf command (I think there is a typo in your documentation for this specific instruction: kopfs -> kopf)
  ```shell
  kopf run --verbose -m fluidos_model_orchestrator
  ```
  
  The result of this procedure generate an error on the last step:
  
```shell
Traceback (most recent call last):
  File "/home/andrea/vscode/fluidos/fluidos-modelbased-metaorchestrator/.venv/bin/kopf", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/andrea/vscode/fluidos/fluidos-modelbased-metaorchestrator/.venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrea/vscode/fluidos/fluidos-modelbased-metaorchestrator/.venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/andrea/vscode/fluidos/fluidos-modelbased-metaorchestrator/.venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrea/vscode/fluidos/fluidos-modelbased-metaorchestrator/.venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrea/vscode/fluidos/fluidos-modelbased-metaorchestrator/.venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrea/vscode/fluidos/fluidos-modelbased-metaorchestrator/.venv/lib/python3.12/site-packages/kopf/cli.py", line 60, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/andrea/vscode/fluidos/fluidos-modelbased-metaorchestrator/.venv/lib/python3.12/site-packages/click/decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrea/vscode/fluidos/fluidos-modelbased-metaorchestrator/.venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrea/vscode/fluidos/fluidos-modelbased-metaorchestrator/.venv/lib/python3.12/site-packages/kopf/cli.py", line 104, in run
    loaders.preload(
  File "/home/andrea/vscode/fluidos/fluidos-modelbased-metaorchestrator/.venv/lib/python3.12/site-packages/kopf/_cogs/helpers/loaders.py", line 46, in preload
    importlib.import_module(name)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'fluidos_model_orchestrator'
``` 

---

I'm not sure if this behavior is due to a bad configuration from my side or something like this. To be sure I tested the development mode even using a cluster created by the [FLUIDOS Node installation script](https://github.com/fluidos-project/node/blob/main/tools/scripts/setup.sh). However a similar output is produced whenI try with the production mode.

---

Production mode
---

1. Building of the docker image, without pushing it (since I will use it in a kind cluster)
```shell
docker build -t fluidos-mbmo:latest . 
```
2. After exporting the KUBECONFIG variable to the cluster, loading the image as suggested in your readme
```shell
docker build -t fluidos-mbmo:latest . 
```
3. Apply of the CRD
```shell
kubectl apply -f utils/fluidos-deployment-crd.yaml
```
4. Apply of the deployment (I needed to edit the deployment image to match with the one you suggest in the first command of building
```shell
kubectl apply -f utils/fluidos-deployment.yaml
```

The result was pretty similar (obtained by log of the Metaorchestrator pod, which is in a _CrashLoopBackOff_ status):
```shell
andrea@ANDREA-DESKTOP:~/vscode/fluidos/fluidos-modelbased-metaorchestrator$ k logs fluidos-modelbased-metaorchestrator-7c8dcd6d7b-49298
Traceback (most recent call last):
  File "/usr/local/bin/kopf", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kopf/cli.py", line 60, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kopf/cli.py", line 104, in run
    loaders.preload(
  File "/usr/local/lib/python3.11/site-packages/kopf/_cogs/helpers/loaders.py", line 46, in preload
    importlib.import_module(name)
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'fluidos_model_orchestrator'
```

---

I don't understand what exactly is wrong, if there is a bug or I executed something wrong in the installation process following your instructions.

Thanks in advance for your help

Andrea

**Comment by stefano81** [comment]
Thank you for the reported issue, we are looking into that.
We are currently upgrading the operator to work with node v0.0.4, and we will release an amended version soon.
